version: "3.4"
services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "uvicorn main:app --reload"
        # environment:
        #     - DB_HOST=db
        #     - DB_NAME=app
        #     - DB_USER=postgres
        #     - DB_PASS=aswin@10
        # depends_on:
        #     - db
    
    # db: 
    #     image: postgress:10-alpine
    #     environment:
    #         - POSTGRES_DB=app
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=aswin@10
       

